language: node_js
cache: yarn
node_js:
- '11'
script:
- npm i bs-platform --no-save
- yarn build
- yarn test
deploy:
  skip_cleanup: true
  provider: npm
  email: rpbiwer@gmail.com
  on:
    tags: true
    branch: master
  api_key:
    secure: zDbET/JMaYd8CduPCS7j0u53Nyi0okXGlqUXQ9zmxbOz3R/TdMYotr3gadJyHb5bEVMHq5d/iqu2Sq8anW12+WfErqKD4Yk0YzhTuqhVGAPdmAdcOQx9wC/DUH4HRCytfh+te7SM/3PRVfuvVY+uWDOcpAhaDDOU4SkcGtCz6NKfCP0OxG7nkSdyi1BnWZ3VjGXXR94KmpEvF1wXue9QZMouOuXnhx0E6IZEEPRdoXDzfWkugnzgJ42uh4mweMYGfaC7yEQzNlRLI5UjRRxago2tVS1YgUUXS+UOEF9X2f01R0MsHTYM19BHtx+SfDgdYfQD+fIGV04Q/zyrJ3W5mzlbVUseW3xsJWshr6AxFZrzoYt2lms32HKbmD5ZoQrEmxIK6ODY5MToS4m1yOwxHkAlwqzhqsJWB/G2GMaOhXa+tdaPskvVpUfgdvOOozZURI59Z/pgILn8VeEX5GYJ8XfC5zTp+PaPKil+BcPzpioVXhAnl2cBdn50uzV+v1ahg5+IQFCBMS9XMt/srXrxKWr0kz3ENl/ULaqEgwfSBtO+H1N4uvJco6gPoEfEcy2jjT+D3WN5D3m9o+w1Y7NocpZcgH0MlwIOEI3NJuX+7BpH/TmFCdfAv+CU+cRBLUEzW3kVO8ab/vqn2HBpxSRZObyg635Iogt1mOZwA143Z/c=
